version: '3'

services:
  redis:
    container_name: gowet-redis
    image: redis:6.2.4
    ports:
      - 6379:6379
  api:
    container_name: gowet-api
    build:
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
